# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# create app directory
WORKDIR /app

# install dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts --no-progress --no-audit

# copy source files
COPY . .

# default command to run the MCP server
CMD ["node", "index.js"]